# Generated by Django 5.1.4 on 2026-06-26 20:49

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("media", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="GameType",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="yaratilgan"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="yangilangan"),
                ),
                (
                    "key",
                    models.SlugField(max_length=32, unique=True, verbose_name="kalit"),
                ),
                ("name_uz", models.CharField(max_length=64, verbose_name="nom (uz)")),
                (
                    "name_ru",
                    models.CharField(
                        blank=True, max_length=64, verbose_name="nom (ru)"
                    ),
                ),
                (
                    "skill",
                    models.CharField(
                        blank=True, max_length=64, verbose_name="ko'nikma"
                    ),
                ),
                (
                    "min_age_band",
                    models.CharField(
                        choices=[
                            ("3-4", "3–4 yosh"),
                            ("5-6", "5–6 yosh"),
                            ("6-7", "6–7 yosh"),
                        ],
                        default="3-4",
                        max_length=8,
                        verbose_name="min yosh",
                    ),
                ),
                (
                    "schema_json",
                    models.JSONField(
                        blank=True, default=dict, verbose_name="config sxemasi"
                    ),
                ),
            ],
            options={
                "verbose_name": "O'yin turi",
                "verbose_name_plural": "O'yin turlari",
                "ordering": ["key"],
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="Language",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="yaratilgan"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="yangilangan"),
                ),
                (
                    "code",
                    models.CharField(max_length=8, unique=True, verbose_name="kod"),
                ),
                ("name", models.CharField(max_length=64, verbose_name="nom")),
            ],
            options={
                "verbose_name": "Til",
                "verbose_name_plural": "Tillar",
                "ordering": ["-created_at"],
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="Lesson",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="yaratilgan"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="yangilangan"),
                ),
                (
                    "order",
                    models.PositiveIntegerField(default=1, verbose_name="tartib"),
                ),
                (
                    "title_uz",
                    models.CharField(max_length=128, verbose_name="sarlavha (uz)"),
                ),
                (
                    "title_ru",
                    models.CharField(
                        blank=True, max_length=128, verbose_name="sarlavha (ru)"
                    ),
                ),
                (
                    "min_age_band",
                    models.CharField(
                        choices=[
                            ("3-4", "3–4 yosh"),
                            ("5-6", "5–6 yosh"),
                            ("6-7", "6–7 yosh"),
                        ],
                        default="3-4",
                        max_length=8,
                        verbose_name="min yosh",
                    ),
                ),
            ],
            options={
                "verbose_name": "Dars",
                "verbose_name_plural": "Darslar",
                "ordering": ["theme", "order"],
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="LessonStep",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="yaratilgan"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="yangilangan"),
                ),
                (
                    "order",
                    models.PositiveIntegerField(default=1, verbose_name="tartib"),
                ),
                (
                    "kind",
                    models.CharField(
                        choices=[
                            ("intro", "Tanishtirish"),
                            ("practice", "Mashq"),
                            ("mastery", "Tekshirish"),
                        ],
                        max_length=12,
                        verbose_name="turi",
                    ),
                ),
                (
                    "config_json",
                    models.JSONField(
                        blank=True, default=dict, verbose_name="konfiguratsiya"
                    ),
                ),
                (
                    "lesson",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="steps",
                        to="content.lesson",
                        verbose_name="dars",
                    ),
                ),
            ],
            options={
                "verbose_name": "Dars qadami",
                "verbose_name_plural": "Dars qadamlari",
                "ordering": ["lesson", "order"],
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="Level",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="yaratilgan"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="yangilangan"),
                ),
                (
                    "order",
                    models.PositiveIntegerField(default=1, verbose_name="tartib"),
                ),
                (
                    "title_uz",
                    models.CharField(max_length=128, verbose_name="sarlavha (uz)"),
                ),
                (
                    "title_ru",
                    models.CharField(
                        blank=True, max_length=128, verbose_name="sarlavha (ru)"
                    ),
                ),
                (
                    "language",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="levels",
                        to="content.language",
                        verbose_name="til",
                    ),
                ),
            ],
            options={
                "verbose_name": "Daraja",
                "verbose_name_plural": "Darajalar",
                "ordering": ["language", "order"],
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="Story",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="yaratilgan"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="yangilangan"),
                ),
                ("title", models.CharField(max_length=128, verbose_name="sarlavha")),
                (
                    "level",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="stories",
                        to="content.level",
                        verbose_name="daraja",
                    ),
                ),
            ],
            options={
                "verbose_name": "Ertak",
                "verbose_name_plural": "Ertaklar",
                "ordering": ["-created_at"],
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="StoryNode",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="yaratilgan"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="yangilangan"),
                ),
                (
                    "order",
                    models.PositiveIntegerField(default=1, verbose_name="tartib"),
                ),
                ("text", models.TextField(blank=True, verbose_name="matn")),
                (
                    "choices_json",
                    models.JSONField(
                        blank=True, default=list, verbose_name="tanlovlar"
                    ),
                ),
                (
                    "audio",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to="media.media",
                    ),
                ),
                (
                    "image",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to="media.media",
                    ),
                ),
                (
                    "story",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="nodes",
                        to="content.story",
                        verbose_name="ertak",
                    ),
                ),
            ],
            options={
                "verbose_name": "Ertak sahnasi",
                "verbose_name_plural": "Ertak sahnalari",
                "ordering": ["story", "order"],
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="Theme",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="yaratilgan"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="yangilangan"),
                ),
                (
                    "order",
                    models.PositiveIntegerField(default=1, verbose_name="tartib"),
                ),
                ("key", models.SlugField(max_length=64, verbose_name="kalit")),
                (
                    "title_uz",
                    models.CharField(max_length=128, verbose_name="sarlavha (uz)"),
                ),
                (
                    "title_ru",
                    models.CharField(
                        blank=True, max_length=128, verbose_name="sarlavha (ru)"
                    ),
                ),
                (
                    "icon",
                    models.CharField(blank=True, max_length=32, verbose_name="ikona"),
                ),
                (
                    "level",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="themes",
                        to="content.level",
                        verbose_name="daraja",
                    ),
                ),
            ],
            options={
                "verbose_name": "Mavzu",
                "verbose_name_plural": "Mavzular",
                "ordering": ["level", "order"],
                "abstract": False,
            },
        ),
        migrations.AddField(
            model_name="lesson",
            name="theme",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="lessons",
                to="content.theme",
                verbose_name="mavzu",
            ),
        ),
        migrations.CreateModel(
            name="Word",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="yaratilgan"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="yangilangan"),
                ),
                ("lemma", models.CharField(max_length=64, verbose_name="so'z")),
                (
                    "translit",
                    models.CharField(
                        blank=True, max_length=64, verbose_name="transliteratsiya"
                    ),
                ),
                (
                    "stress_index",
                    models.IntegerField(
                        blank=True, null=True, verbose_name="urg'u indeksi"
                    ),
                ),
                (
                    "l1_translation_json",
                    models.JSONField(
                        blank=True, default=dict, verbose_name="ona tili tarjimasi"
                    ),
                ),
                (
                    "difficulty",
                    models.PositiveIntegerField(default=1, verbose_name="qiyinlik"),
                ),
                (
                    "part_of_speech",
                    models.CharField(
                        choices=[
                            ("noun", "Ot"),
                            ("verb", "Fe'l"),
                            ("adj", "Sifat"),
                            ("other", "Boshqa"),
                        ],
                        default="noun",
                        max_length=8,
                        verbose_name="so'z turkumi",
                    ),
                ),
                (
                    "gender",
                    models.CharField(
                        choices=[
                            ("m", "Erkak (м)"),
                            ("f", "Ayol (ж)"),
                            ("n", "Hech (ср)"),
                            ("-", "—"),
                        ],
                        default="-",
                        max_length=2,
                        verbose_name="rod",
                    ),
                ),
                (
                    "plural_form",
                    models.CharField(blank=True, max_length=64, verbose_name="ko'plik"),
                ),
                (
                    "freq_rank",
                    models.PositiveIntegerField(
                        blank=True, null=True, verbose_name="chastota o'rni"
                    ),
                ),
                (
                    "is_cognate_uz",
                    models.BooleanField(default=False, verbose_name="o'zbekcha kognat"),
                ),
                (
                    "audio_native",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to="media.media",
                    ),
                ),
                (
                    "image",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to="media.media",
                    ),
                ),
                (
                    "language",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="words",
                        to="content.language",
                        verbose_name="til",
                    ),
                ),
                (
                    "theme",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="words",
                        to="content.theme",
                        verbose_name="mavzu",
                    ),
                ),
            ],
            options={
                "verbose_name": "So'z",
                "verbose_name_plural": "So'zlar",
                "ordering": ["theme", "freq_rank", "lemma"],
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="Song",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="yaratilgan"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="yangilangan"),
                ),
                ("title", models.CharField(max_length=128, verbose_name="sarlavha")),
                (
                    "lyrics_json",
                    models.JSONField(
                        blank=True, default=list, verbose_name="matn (lyrics)"
                    ),
                ),
                (
                    "audio",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to="media.media",
                    ),
                ),
                (
                    "theme",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="songs",
                        to="content.theme",
                        verbose_name="mavzu",
                    ),
                ),
                (
                    "words",
                    models.ManyToManyField(
                        blank=True, related_name="songs", to="content.word"
                    ),
                ),
            ],
            options={
                "verbose_name": "Qo'shiq",
                "verbose_name_plural": "Qo'shiqlar",
                "ordering": ["-created_at"],
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="Phrase",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="yaratilgan"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="yangilangan"),
                ),
                ("text", models.CharField(max_length=255, verbose_name="matn")),
                (
                    "l1_translation_json",
                    models.JSONField(
                        blank=True, default=dict, verbose_name="ona tili tarjimasi"
                    ),
                ),
                (
                    "audio",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to="media.media",
                    ),
                ),
                (
                    "language",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="phrases",
                        to="content.language",
                        verbose_name="til",
                    ),
                ),
                (
                    "words",
                    models.ManyToManyField(
                        blank=True, related_name="phrases", to="content.word"
                    ),
                ),
            ],
            options={
                "verbose_name": "Ibora",
                "verbose_name_plural": "Iboralar",
                "ordering": ["-created_at"],
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="Letter",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="yaratilgan"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="yangilangan"),
                ),
                ("char", models.CharField(max_length=4, verbose_name="harf")),
                (
                    "sound_ipa",
                    models.CharField(
                        blank=True, max_length=16, verbose_name="tovush (IPA)"
                    ),
                ),
                (
                    "mnemonic_text",
                    models.CharField(
                        blank=True, max_length=255, verbose_name="mnemonik"
                    ),
                ),
                (
                    "group_no",
                    models.PositiveIntegerField(default=1, verbose_name="guruh"),
                ),
                (
                    "order",
                    models.PositiveIntegerField(default=1, verbose_name="tartib"),
                ),
                (
                    "audio",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to="media.media",
                    ),
                ),
                (
                    "language",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="letters",
                        to="content.language",
                        verbose_name="til",
                    ),
                ),
                (
                    "mnemonic_image",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to="media.media",
                    ),
                ),
            ],
            options={
                "verbose_name": "Harf",
                "verbose_name_plural": "Harflar",
                "ordering": ["language", "group_no", "order"],
                "abstract": False,
                "constraints": [
                    models.UniqueConstraint(
                        fields=("language", "char"), name="uniq_letter"
                    )
                ],
            },
        ),
        migrations.AddConstraint(
            model_name="word",
            constraint=models.UniqueConstraint(
                fields=("language", "lemma"), name="uniq_word"
            ),
        ),
    ]
