# Generated by Django 5.1.4 on 2026-06-26 21:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("content", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="word",
            name="confusable_with",
            field=models.ManyToManyField(
                blank=True,
                to="content.word",
                verbose_name="chalkashtiruvchi (o'xshash)",
            ),
        ),
    ]
