# Generated by Django 5.1.4 on 2026-06-27 15:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("content", "0002_word_confusable_with"),
    ]

    operations = [
        migrations.AddField(
            model_name="gametype",
            name="dimension",
            field=models.CharField(
                choices=[
                    ("receptive", "Reseptiv (tanib olish)"),
                    ("expressive", "Ekspressiv (ishlab chiqarish)"),
                ],
                default="receptive",
                max_length=12,
                verbose_name="o'lcham (SRS)",
            ),
        ),
    ]
