# Generated by Django 5.1.4 on 2026-06-27 00:25

import django.db.models.deletion
import django.utils.timezone
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("accounts", "0002_childprofile_current_level"),
    ]

    operations = [
        migrations.CreateModel(
            name="ItemState",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="yaratilgan"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="yangilangan"),
                ),
                (
                    "item_type",
                    models.CharField(
                        choices=[("word", "So'z"), ("letter", "Harf")],
                        max_length=8,
                        verbose_name="tur",
                    ),
                ),
                ("item_id", models.UUIDField(verbose_name="item id")),
                (
                    "stability",
                    models.FloatField(default=0.0, verbose_name="barqarorlik (kun)"),
                ),
                ("difficulty", models.FloatField(default=0.3, verbose_name="qiyinlik")),
                (
                    "due_at",
                    models.DateTimeField(
                        db_index=True,
                        default=django.utils.timezone.now,
                        verbose_name="muddati",
                    ),
                ),
                (
                    "last_reviewed_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="oxirgi takror"
                    ),
                ),
                (
                    "reps",
                    models.PositiveIntegerField(
                        default=0, verbose_name="muvaffaqiyatli takrorlar"
                    ),
                ),
                (
                    "lapses",
                    models.PositiveIntegerField(default=0, verbose_name="unutishlar"),
                ),
                (
                    "receptive_strength",
                    models.FloatField(default=0.0, verbose_name="reseptiv kuch"),
                ),
                (
                    "expressive_strength",
                    models.FloatField(default=0.0, verbose_name="ekspressiv kuch"),
                ),
                (
                    "exposures",
                    models.PositiveIntegerField(default=0, verbose_name="ko'rishlar"),
                ),
                (
                    "last_result",
                    models.BooleanField(
                        blank=True, null=True, verbose_name="oxirgi natija"
                    ),
                ),
                (
                    "child",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="item_states",
                        to="accounts.childprofile",
                        verbose_name="bola",
                    ),
                ),
            ],
            options={
                "verbose_name": "Item holati (SRS)",
                "verbose_name_plural": "Item holatlari (SRS)",
                "indexes": [
                    models.Index(
                        fields=["child", "due_at"],
                        name="learning_it_child_i_ab7d7f_idx",
                    )
                ],
                "constraints": [
                    models.UniqueConstraint(
                        fields=("child", "item_type", "item_id"),
                        name="uniq_child_item_state",
                    )
                ],
            },
        ),
        migrations.CreateModel(
            name="LearningEvent",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="yaratilgan"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="yangilangan"),
                ),
                (
                    "event_id",
                    models.UUIDField(
                        db_index=True,
                        unique=True,
                        verbose_name="event id (idempotentlik)",
                    ),
                ),
                (
                    "item_type",
                    models.CharField(
                        choices=[("word", "So'z"), ("letter", "Harf")],
                        max_length=8,
                        verbose_name="tur",
                    ),
                ),
                ("item_id", models.UUIDField(verbose_name="item id")),
                (
                    "game_type",
                    models.CharField(
                        blank=True, default="", max_length=32, verbose_name="o'yin turi"
                    ),
                ),
                (
                    "is_correct",
                    models.BooleanField(default=False, verbose_name="to'g'ri"),
                ),
                (
                    "latency_ms",
                    models.PositiveIntegerField(
                        blank=True, null=True, verbose_name="kechikish (ms)"
                    ),
                ),
                (
                    "hint_used",
                    models.BooleanField(
                        default=False, verbose_name="maslahat ishlatildi"
                    ),
                ),
                (
                    "session_id",
                    models.CharField(
                        blank=True, default="", max_length=64, verbose_name="sessiya id"
                    ),
                ),
                (
                    "ts",
                    models.DateTimeField(
                        db_index=True,
                        default=django.utils.timezone.now,
                        verbose_name="vaqt",
                    ),
                ),
                (
                    "child",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="learning_events",
                        to="accounts.childprofile",
                        verbose_name="bola",
                    ),
                ),
            ],
            options={
                "verbose_name": "O'rganish hodisasi",
                "verbose_name_plural": "O'rganish hodisalari",
                "indexes": [
                    models.Index(
                        fields=["child", "ts"], name="learning_le_child_i_cad8bb_idx"
                    )
                ],
            },
        ),
    ]
