# Generated by Django 5.1.4 on 2026-06-26 19:48

import apps.accounts.models
import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("auth", "0012_alter_user_first_name_max_length"),
    ]

    operations = [
        migrations.CreateModel(
            name="ParentAccount",
            fields=[
                ("password", models.CharField(max_length=128, verbose_name="password")),
                (
                    "last_login",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="last login"
                    ),
                ),
                (
                    "is_superuser",
                    models.BooleanField(
                        default=False,
                        help_text="Designates that this user has all permissions without explicitly assigning them.",
                        verbose_name="superuser status",
                    ),
                ),
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "phone",
                    models.CharField(
                        blank=True,
                        max_length=32,
                        null=True,
                        unique=True,
                        verbose_name="telefon",
                    ),
                ),
                (
                    "email",
                    models.EmailField(
                        blank=True,
                        max_length=254,
                        null=True,
                        unique=True,
                        verbose_name="email",
                    ),
                ),
                (
                    "full_name",
                    models.CharField(
                        blank=True, max_length=255, verbose_name="F.I.Sh."
                    ),
                ),
                (
                    "locale",
                    models.CharField(default="uz", max_length=8, verbose_name="til"),
                ),
                ("is_active", models.BooleanField(default=True)),
                ("is_staff", models.BooleanField(default=False)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "groups",
                    models.ManyToManyField(
                        blank=True,
                        help_text="The groups this user belongs to. A user will get all permissions granted to each of their groups.",
                        related_name="user_set",
                        related_query_name="user",
                        to="auth.group",
                        verbose_name="groups",
                    ),
                ),
                (
                    "user_permissions",
                    models.ManyToManyField(
                        blank=True,
                        help_text="Specific permissions for this user.",
                        related_name="user_set",
                        related_query_name="user",
                        to="auth.permission",
                        verbose_name="user permissions",
                    ),
                ),
            ],
            options={
                "verbose_name": "Ota-ona akkaunti",
                "verbose_name_plural": "Ota-ona akkauntlari",
                "ordering": ["-created_at"],
            },
            managers=[
                ("objects", apps.accounts.models.ParentManager()),
            ],
        ),
        migrations.CreateModel(
            name="ChildProfile",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="yaratilgan"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="yangilangan"),
                ),
                (
                    "display_name",
                    models.CharField(max_length=64, verbose_name="ism / taxallus"),
                ),
                (
                    "avatar_id",
                    models.CharField(
                        choices=[
                            ("mishka", "Mishka (ayiq)"),
                            ("zayka", "Zayka (quyon)"),
                            ("kotik", "Kotik (mushuk)"),
                            ("sobachka", "Sobachka (kuchuk)"),
                            ("lisichka", "Lisichka (tulki)"),
                            ("ptichka", "Ptichka (qush)"),
                        ],
                        default="mishka",
                        max_length=32,
                        verbose_name="avatar",
                    ),
                ),
                (
                    "age_band",
                    models.CharField(
                        choices=[
                            ("3-4", "3–4 yosh"),
                            ("5-6", "5–6 yosh"),
                            ("6-7", "6–7 yosh"),
                        ],
                        default="3-4",
                        max_length=8,
                        verbose_name="yosh diapazoni",
                    ),
                ),
                (
                    "l1_locale",
                    models.CharField(
                        default="uz", max_length=8, verbose_name="ona tili"
                    ),
                ),
                (
                    "pin",
                    models.CharField(
                        blank=True,
                        default="",
                        max_length=128,
                        verbose_name="PIN (hash)",
                    ),
                ),
                ("is_active", models.BooleanField(default=True)),
                (
                    "parent",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="children",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="ota-ona",
                    ),
                ),
            ],
            options={
                "verbose_name": "Bola profili",
                "verbose_name_plural": "Bola profillari",
                "ordering": ["-created_at"],
                "abstract": False,
            },
        ),
    ]
