# Generated by Django 5.1.4 on 2026-06-26 21:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0001_initial"),
        ("content", "0002_word_confusable_with"),
    ]

    operations = [
        migrations.AddField(
            model_name="childprofile",
            name="current_level",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="+",
                to="content.level",
                verbose_name="joriy daraja",
            ),
        ),
    ]
