# Generated by Django 5.1.4 on 2026-06-27 16:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0002_childprofile_current_level"),
    ]

    operations = [
        migrations.AddField(
            model_name="childprofile",
            name="daily_limit_minutes",
            field=models.PositiveIntegerField(
                blank=True, null=True, verbose_name="kunlik limit (daq)"
            ),
        ),
    ]
