# Generated by Django 5.1.4 on 2026-06-26 20:49

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Media",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="yaratilgan"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="yangilangan"),
                ),
                (
                    "kind",
                    models.CharField(
                        choices=[
                            ("audio", "Audio"),
                            ("image", "Rasm"),
                            ("lottie", "Lottie"),
                        ],
                        max_length=8,
                        verbose_name="tur",
                    ),
                ),
                (
                    "title",
                    models.CharField(blank=True, max_length=200, verbose_name="nom"),
                ),
                (
                    "file",
                    models.FileField(
                        blank=True, upload_to="content/", verbose_name="fayl"
                    ),
                ),
                (
                    "duration_ms",
                    models.PositiveIntegerField(
                        blank=True,
                        help_text="Audio uchun",
                        null=True,
                        verbose_name="davomiylik (ms)",
                    ),
                ),
                (
                    "meta",
                    models.JSONField(blank=True, default=dict, verbose_name="meta"),
                ),
            ],
            options={
                "verbose_name": "Media",
                "verbose_name_plural": "Media",
                "ordering": ["-created_at"],
                "abstract": False,
            },
        ),
    ]
