# Generated by Django 5.1.4 on 2026-06-26 22:07

import apps.media.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("media", "0002_alter_media_file"),
    ]

    operations = [
        migrations.AlterField(
            model_name="media",
            name="file",
            field=models.FileField(
                blank=True,
                upload_to=apps.media.models.media_upload_to,
                validators=[apps.media.models.validate_media_file],
                verbose_name="fayl",
            ),
        ),
    ]
