# Generated by Django 5.1.4 on 2026-06-27 16:37

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("accounts", "0003_childprofile_daily_limit_minutes"),
    ]

    operations = [
        migrations.CreateModel(
            name="Achievement",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="yaratilgan"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="yangilangan"),
                ),
                (
                    "key",
                    models.SlugField(max_length=48, unique=True, verbose_name="kalit"),
                ),
                ("title_uz", models.CharField(max_length=120, verbose_name="nom (uz)")),
                (
                    "title_ru",
                    models.CharField(
                        blank=True, max_length=120, verbose_name="nom (ru)"
                    ),
                ),
                (
                    "category",
                    models.CharField(
                        choices=[
                            ("milestone", "Bosqich"),
                            ("theme", "Mavzu"),
                            ("streak", "Ketma-ketlik"),
                            ("alphabet", "Alifbo"),
                        ],
                        default="milestone",
                        max_length=16,
                        verbose_name="kategoriya",
                    ),
                ),
                (
                    "icon",
                    models.CharField(
                        default="🏅", max_length=8, verbose_name="ikona (placeholder)"
                    ),
                ),
                (
                    "rule_json",
                    models.JSONField(default=dict, verbose_name="ochilish sharti"),
                ),
                (
                    "order",
                    models.PositiveIntegerField(default=1, verbose_name="tartib"),
                ),
            ],
            options={
                "verbose_name": "Yutuq",
                "verbose_name_plural": "Yutuqlar",
                "ordering": ["order", "key"],
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="ForestElement",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="yaratilgan"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="yangilangan"),
                ),
                (
                    "key",
                    models.SlugField(max_length=48, unique=True, verbose_name="kalit"),
                ),
                ("title_uz", models.CharField(max_length=120, verbose_name="nom (uz)")),
                (
                    "title_ru",
                    models.CharField(
                        blank=True, max_length=120, verbose_name="nom (ru)"
                    ),
                ),
                (
                    "asset_slot",
                    models.CharField(
                        default="🌳", max_length=8, verbose_name="asset (placeholder)"
                    ),
                ),
                (
                    "rule_json",
                    models.JSONField(default=dict, verbose_name="ochilish sharti"),
                ),
                (
                    "order",
                    models.PositiveIntegerField(default=1, verbose_name="tartib"),
                ),
            ],
            options={
                "verbose_name": "O'rmon elementi",
                "verbose_name_plural": "O'rmon elementlari",
                "ordering": ["order", "key"],
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="MishkaItem",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="yaratilgan"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="yangilangan"),
                ),
                (
                    "key",
                    models.SlugField(max_length=48, unique=True, verbose_name="kalit"),
                ),
                ("title_uz", models.CharField(max_length=120, verbose_name="nom (uz)")),
                (
                    "title_ru",
                    models.CharField(
                        blank=True, max_length=120, verbose_name="nom (ru)"
                    ),
                ),
                (
                    "slot",
                    models.CharField(default="hat", max_length=16, verbose_name="slot"),
                ),
                (
                    "asset_slot",
                    models.CharField(
                        default="🎩", max_length=8, verbose_name="asset (placeholder)"
                    ),
                ),
                (
                    "rule_json",
                    models.JSONField(default=dict, verbose_name="ochilish sharti"),
                ),
                (
                    "order",
                    models.PositiveIntegerField(default=1, verbose_name="tartib"),
                ),
            ],
            options={
                "verbose_name": "Mishka buyumi",
                "verbose_name_plural": "Mishka buyumlari",
                "ordering": ["order", "key"],
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="StreakRecord",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="yaratilgan"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="yangilangan"),
                ),
                (
                    "current",
                    models.PositiveIntegerField(
                        default=0, verbose_name="joriy ketma-ketlik"
                    ),
                ),
                (
                    "longest",
                    models.PositiveIntegerField(default=0, verbose_name="eng uzun"),
                ),
                (
                    "last_active_date",
                    models.DateField(
                        blank=True, null=True, verbose_name="oxirgi faol kun"
                    ),
                ),
                (
                    "child",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="streak",
                        to="accounts.childprofile",
                    ),
                ),
            ],
            options={
                "verbose_name": "Streak",
                "verbose_name_plural": "Streaklar",
                "ordering": ["-created_at"],
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="ChildAchievement",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="yaratilgan"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="yangilangan"),
                ),
                ("seen", models.BooleanField(default=False, verbose_name="ko'rilgan")),
                (
                    "achievement",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="+",
                        to="gamification.achievement",
                    ),
                ),
                (
                    "child",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="achievements",
                        to="accounts.childprofile",
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
                "abstract": False,
                "constraints": [
                    models.UniqueConstraint(
                        fields=("child", "achievement"), name="uniq_child_achievement"
                    )
                ],
            },
        ),
        migrations.CreateModel(
            name="ChildForestElement",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="yaratilgan"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="yangilangan"),
                ),
                ("seen", models.BooleanField(default=False, verbose_name="ko'rilgan")),
                (
                    "child",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="forest_elements",
                        to="accounts.childprofile",
                    ),
                ),
                (
                    "element",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="+",
                        to="gamification.forestelement",
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
                "abstract": False,
                "constraints": [
                    models.UniqueConstraint(
                        fields=("child", "element"), name="uniq_child_forest_element"
                    )
                ],
            },
        ),
        migrations.CreateModel(
            name="ChildMishkaItem",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="yaratilgan"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="yangilangan"),
                ),
                ("seen", models.BooleanField(default=False, verbose_name="ko'rilgan")),
                (
                    "child",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="mishka_items",
                        to="accounts.childprofile",
                    ),
                ),
                (
                    "item",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="+",
                        to="gamification.mishkaitem",
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
                "abstract": False,
                "constraints": [
                    models.UniqueConstraint(
                        fields=("child", "item"), name="uniq_child_mishka_item"
                    )
                ],
            },
        ),
    ]
